


const settingTypes = {
    SET_MAP_FILL_COLOR: "SET_MAP_FILL_COLOR",
    SET_MAP_STROKE_COLOR: "SET_MAP_STROKE_COLOR",
    SET_MARKER_FILL_COLOR: "SET_MARKER_FILL_COLOR",
    SET_MARKER_STROKE_COLOR: "SET_MARKER_STROKE_COLOR",
    SET_MARKER_STROKE_WIDTH: "SET_MARKER_STROKE_WIDTH",
    SET_MARKER_SIZE: "SET_MARKER_SIZE",
    SET_TEXT_OFFSET: "SET_TEXT_OFFSET",
    ADD_MARKER: "ADD_MARKER",
    REMOVE_MARKER: "REMOVE_MARKER"
    
}

export default settingTypes;