


const settingTypes = {
    SET_MAP_FILL_COLOR: "SET_MAP_FILL_COLOR",
    SET_MAP_STROKE_COLOR: "SET_MAP_STROKE_COLOR",
    SET_MARKER_FILL_COLOR: "SET_MARKER_FILL_COLOR",
    SET_MARKER_FILL_COLOR_FOR_MARKER: "SET_MARKER_FILL_COLOR_FOR_MARKER",
    SET_MARKER_TEXT_COLOR: "SET_MARKER_TEXT_COLOR",
    SET_MARKER_TEXT_COLOR_FOR_MARKER: "SET_MARKER_TEXT_COLOR_FOR_MARKER",
    SET_MARKER_FONT_SIZE: "SET_MARKER_FONT_SIZE",
    SET_MARKER_FONT_SIZE_FOR_MARKER: "SET_MARKER_FONT_SIZE_FOR_MARKER",
    SET_MARKER_STROKE_COLOR: "SET_MARKER_STROKE_COLOR",
    SET_MARKER_STROKE_COLOR_FOR_MARKER: "SET_MARKER_STROKE_COLOR_FOR_MARKER",
    SET_MARKER_STROKE_WIDTH: "SET_MARKER_STROKE_WIDTH",
    SET_MARKER_STROKE_WIDTH_FOR_MARKER: "SET_MARKER_STROKE_WIDTH_FOR_MARKER",
    SET_MARKER_SIZE: "SET_MARKER_SIZE",
    SET_MARKER_SIZE_FOR_MARKER: "SET_MARKER_SIZE_FOR_MARKER",
    SET_TEXT_OFFSET_Y: "SET_TEXT_OFFSET_Y",
    SET_TEXT_OFFSET_X: "SET_TEXT_OFFSET_X",
    SET_TEXT_OFFSET_Y_FOR_MARKER: "SET_TEXT_OFFSET_Y_FOR_MARKER",
    SET_TEXT_OFFSET_X_FOR_MARKER: "SET_TEXT_OFFSET_X_FOR_MARKER",
    ADD_MARKER: "ADD_MARKER",
    REMOVE_MARKER: "REMOVE_MARKER"
    
}

export default settingTypes;